### ISSUE TITLE
Add screenshots to description

### ISSUE THREAD

**Issue by Nick2bad4u** [Jinxer42/Save-Evil-Creatures#2]
Can you add some screenshots to the description so we can get an idea of what this is/does?

😎

**Comment by Jinxer42** [comment]
I don't know if it is worth doing a pull request just for the screenshots, but I updated it on my version to have them which you can see here:

https://github.com/Jinxer42/Save-Evil-Creatures/blob/master/README.md

Enjoy the adorableness of them!

**Comment by Nick2bad4u** [comment]
Thats cute, thanks!
